import express from "express"
import PDFDocument from "pdfkit"
import InterviewSession from "../models/InterviewSession.js"
import LiveInterview from "../models/LiveInterview.js"

const router = express.Router()

router.get("/interview/:type/:id", async (req, res) => {
  try {
    const { type, id } = req.params

    let session

    if (type === "live") {
      session = await LiveInterview.findById(id)
    } else {
      session = await InterviewSession.findById(id)
    }

    if (!session) {
      return res.status(404).json({
        success: false,
        message: "Interview session not found"
      })
    }

    const doc = new PDFDocument({
      margin: 50
    })

    const fileName = `prep-ai-interview-report-${id}.pdf`

    res.setHeader("Content-Type", "application/pdf")
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${fileName}"`
    )

    doc.pipe(res)

    doc
      .fontSize(24)
      .fillColor("#111827")
      .text("Prep AI Interview Report", {
        align: "center"
      })

    doc.moveDown()

    doc.fontSize(14).fillColor("#374151")
    doc.text(`Interview Type: ${type === "live" ? "Live Interview" : "AI Interview"}`)
    doc.text(`Role: ${session.role || "N/A"}`)
    doc.text(`Difficulty: ${session.difficulty || "N/A"}`)
    doc.text(`Total Score: ${session.totalScore || 0}%`)
    doc.text(`Completed: ${session.completed ? "Yes" : "No"}`)
    doc.text(`Date: ${new Date(session.createdAt).toLocaleString("en-IN")}`)

    if (session.recordingUrl) {
      doc.text(`Recording Link: ${session.recordingUrl}`)
    }

    doc.moveDown()
    doc.fontSize(18).fillColor("#111827").text("Questions & Answers")
    doc.moveDown(0.5)

    const answers = session.answers || []

    if (answers.length === 0) {
      doc.fontSize(12).fillColor("#6b7280").text("No answers found.")
    }

    answers.forEach((item, index) => {
      doc
        .fontSize(14)
        .fillColor("#111827")
        .text(`Question ${index + 1}`, {
          underline: true
        })

      doc.moveDown(0.3)

      doc.fontSize(12).fillColor("#374151")
      doc.text(`Q: ${item.question || "N/A"}`)

      doc.moveDown(0.3)

      doc.text(`Answer: ${item.answer || item.transcript || "N/A"}`)

      doc.moveDown(0.3)

      doc.text(`Score: ${item.score || 0}%`)

      doc.moveDown(0.3)

      doc.text(`Feedback: ${item.feedback || "No feedback available."}`)

      if (item.strengths?.length > 0) {
        doc.moveDown(0.3)
        doc.text(`Strengths: ${item.strengths.join(", ")}`)
      }

      if (item.weaknesses?.length > 0) {
        doc.moveDown(0.3)
        doc.text(`Weaknesses: ${item.weaknesses.join(", ")}`)
      }

      if (item.improvedAnswer) {
        doc.moveDown(0.3)
        doc.text(`Improved Answer: ${item.improvedAnswer}`)
      }

      doc.moveDown()
    })

    doc.moveDown()

    doc
      .fontSize(18)
      .fillColor("#111827")
      .text("Final Improvement Suggestions")

    doc.moveDown(0.5)

    const totalScore = session.totalScore || 0

    let suggestion =
      "Keep practicing regularly and focus on structured, example-based answers."

    if (totalScore >= 80) {
      suggestion =
        "Strong performance. Focus on advanced technical depth, confidence and concise delivery."
    } else if (totalScore >= 60) {
      suggestion =
        "Good attempt. Improve answer structure, add real project examples and explain trade-offs clearly."
    } else {
      suggestion =
        "Needs improvement. Practice fundamentals, prepare STAR-format answers and revise project explanations."
    }

    doc.fontSize(12).fillColor("#374151").text(suggestion)

    doc.moveDown(2)

    doc
      .fontSize(10)
      .fillColor("#6b7280")
      .text("Generated by Prep AI", {
        align: "center"
      })

    doc.end()
  } catch (error) {
    console.log("PDF report error:", error)

    res.status(500).json({
      success: false,
      message: "PDF report generation failed",
      error: error.message
    })
  }
})

export default router